name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: pwsh
      run: ./build.ps1
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: pwsh
      run: ./build.ps1
  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: pwsh
      run: ./build.ps1
